# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('status_id', models.CharField(max_length=1000)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('consumer_key', models.CharField(max_length=1000)),
                ('consumer_secret', models.CharField(max_length=1000)),
                ('access_token', models.CharField(max_length=1000)),
                ('access_token_secret', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='twit',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.TwitterApp'),
        ),
    ]
