# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterapp',
            name='tag',
            field=models.CharField(default='.', max_length=500),
            preserve_default=False,
        ),
    ]
